### ISSUE TITLE
Items with durability are duped through the shift button

### ISSUE THREAD

**Issue by bigenergy** [tth05/morerefinedstorage#3] opened 2020-08-30 13:28 UTC
#### Issue description:
Items with durability are duped through the shift button

#### Steps to reproduce:
1. In the crafting terminal, you lay out the craft of the item (it is imperative that items with durability are used in the craft), you craft it by shift, it is transferred to your inventory, and the ingredients are not spent.
![image](https://user-images.githubusercontent.com/17977139/91660178-70d68380-eadd-11ea-8b7f-9ff6488a8897.png)

2. If there is an item in the upper left slot, and a stack of items in the system, then it will look like this
![image](https://user-images.githubusercontent.com/17977139/91660191-80ee6300-eadd-11ea-9a68-6d395f483a11.png)
![image](https://user-images.githubusercontent.com/17977139/91660198-877cda80-eadd-11ea-90a4-e14d53794776.png)
![image](https://user-images.githubusercontent.com/17977139/91660201-8cda2500-eadd-11ea-88da-c654b2e9060e.png)

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: latest 1.12.2
- Refined Storage: Release v2.1.0

Does this issue occur on a server? [yes/no] yes

**Comment by tth05** [comment] 2020-08-30 14:37
I'm unable to reproduce this in my test world with IC2. Where are those recipes from? They might be doing something special

**Comment by bigenergy** [comment] 2020-08-30 14:39
it even works with vanilla minecraft recipes
![unknown](https://user-images.githubusercontent.com/17977139/91661933-ca43b000-eae7-11ea-989d-2dd4d1f82e95.png)

**Comment by tth05** [comment] 2020-08-30 14:59
Thanks, I was just testing it wrong. New release will be out in a bit!

**Comment by tth05** [comment] 2020-08-30 15:09
Fixed in b094cc44d37443bd17e6e20c893d27b4e5bba7cb

**Closed as completed by tth05** 2020-08-30 15:09 UTC
Labels: bug
